
language: node_js

node_js: 8

git:
  depth: 8

cache:
  directories:
    - node_modules ## NPM packages.

# install: npm install

before_script: npm run build

# script: npm test

after_script: ls -al dist/ index.js

# End.
